#!/usr/bin/env python3.6
from user import User
from random import *
import string

def signup_user(first_name,last_name,username,email,password):
    '''
    Function to sign up a new user
    '''
    new_user = User(first_name,last_name,username,email,password)
    return new_user

def save_users(the_list):
    '''
    Function to save a user
    '''
    return User.save_user(the_list)

def generate_password(passlength):
    '''
    Function to generate a new password
    '''
    mypassword = "".join(choice(string.ascii_letters) for x in range(randint(passlength,passlength)))

    return mypassword

def authenticate_user(username,password):
    '''
    Function to authenticate user details for access
    '''
    User.verify_user(username,password)

def signup_credentials(platform,f_name,l_name,username,email,password,credential_list):
    '''
    Function to add a new credential
    '''
    new_signup = User.create_credential(platform,f_name,l_name,username,email,password)
    User.save_credential(new_signup,credential_list)

def show_credentials(credential_list):
    '''
    Function to show a users' credentials
    '''
    User.display_credential(credential_list)

def main():
    print("Hello Welcome to PassLock. What is your name?")
    user_name = input()
    print(f"Hello {user_name}. what would you like to do?")
    print('\n')

    while True:
                    print("""Use these short codes : 
                    1. Sign Up to PassLock
                    2. Sign Into PassLock
                    3. Register new social media account
                    4. View locker
                    5. Delete account
                    6. Sign out""")

                    short_code = input()

                    if short_code == '1':
                            print("Sign up new user")
                            print("-"*10)

                            print ("First name ....")
                            first_name = input()

                            print("Last name ...")
                            last_name = input()

                            print("Preferred username ...")
                            username = input()

                            print("Email address ...")
                            email = input()

                            print("Password ...")
                            print("Would you like an autogenerated password? [Y/n]")
                            passprompt = input()
                            if passprompt == "Y":
                                print("Length of the password?")
                                passlength = int(input())
                                password = generate_password(passlength)
                            else:
                                print("Type password ...")
                                password = input()

                                curruser = signup_user(first_name,last_name,username,email,password)
                                login_list = save_users(curruser,a_list)
                                print (login_list)
                                print(f"New User {first_name} {last_name} signed up")
                                print ('\n')
                            

                    elif short_code == '2':

                        print("Welcome back to passlock")
                        print("-"*10)
                        print("Kindly enter your username")
                        username = input()
                        print("Password:")
                        password = input()
                        print(authenticate_user(username,password))
                        if (authentication == True):
                            print("Sign in succesful,you can now access your locker")
                        
                        else: 
                            print("Sign in unsuccesful. Try again")


                    else:
                            print("I really didn't get that. Please enter a valid number")

if __name__ == '__main__':

    main()


