#!/usr/bin/env python3.6
from user import User
from credential import Credential
from random import *
import string

def signup_user(first_name,last_name,username,email,password):
    '''
    Function to sign up a new user
    '''
    new_user = User(first_name,last_name,username,email,password)
    return new_user

def generate_password(passlength):
    '''
    Function to generate a new password
    '''
    mypassword = "".join(choice(string.ascii_letters) for x in range(randint(passlength,passlength)))

    return mypassword

def authenticate_user(user,username,password):
    '''
    Function to authenticate user details for access
    '''
    if user.username == username and user.password == password:
        return True

    else:
        return False

def signup_credentials(platform,f_name,l_name,username,email,password):
    '''
    Function to add a new credential
    '''
    return User.create_credential(platform,f_name,l_name,username,email,password)

def save_credentials(credential,credential_list):
    '''
    Function to append new credential
    '''
    return User.save_credential(credential,credential_list)

def show_credentials(credential_list):
    '''
    Function to show a users' credentials
    '''
    return User.display_credentials(credential_list)

def delete_credential(name,credential_list):
    '''
    Function to show a users' credentials
    '''
    return User.del_credential(credential_list)

def main():
    print("Hello Welcome to PassLock. What is your name?")
    user_name = input()
    print(f"Hello {user_name}. Sign Up for PassLock")
    print("Sign up new user")
    print("-"*10)

    print ("First name ....")
    first_name = input()

    print("Last name ...")
    last_name = input()

    print("Preferred username ...")
    username = input()

    print("Email address ...")
    email = input()

    print("Password ...")
    print("Would you like an autogenerated password? [Y/n]")
    passprompt = input()
    if passprompt == "Y":
        print("Length of the password?")
        passlength = int(input())
        password = generate_password(passlength)
        print("Kindly note down your password for sign in")
        print(password                       )
    else:
        print("Type password ...")
        password = input()
        print("Kindly note down your password for sign in")
        print(password)
        curruser = signup_user(first_name,last_name,username,email,password)
        print(f"New User {first_name} {last_name} signed up")
        print("Welcome back to passlock")
        print("-"*10)
        print("Kindly enter your details to sign in")
        print("Username:")
        username = input()
        print("Password:")
        password = input()
        authentication = authenticate_user(curruser,username,password)
        if authentication == True:
            print("Sign in successful. Passlock account is ready")
            while True:
                a_list = []
                print ("""Use these short codes : 
                    1. Register new social media account
                    2. Sign out""")
                shortcode = input()
                if shortcode == '1':
                    print("Register a new social media account")

                    print("Which is the social media platform?")
                    platform = input()

                    print (f"First name on {platform} ...")
                    first_name = input()

                    print(f"Last name on {platform} ...")
                    last_name = input()

                    print(f"Username on {platform}...")
                    username = input()

                    print(f"Email address used for {platform}...")
                    email = input()

                    print("Password ...")
                    print(f"Do you have a password for your {platform} account? [Y/n]")
                    passprompt = input()
                    if passprompt == "Y":
                        print("Type password ...")
                        password = input()
                    else:
                        print("Would you like an autogenerated password? [Y/n]")
                        passprompt = input()
                        if passprompt == "Y":
                            passlength = int(input())
                            password = generate_password(passlength)
                        else:
                            print("Type password ...")
                            password = input()
                            print("Password generated! ...")
                    cred = signup_credentials(platform,first_name,last_name,username,email,password)
                    save_credentials(cred,a_list)
                    print(f"Details for {platform} are now saved")
                    print("""What would you like to do next?
                                1. View locker
                                2. Sign out""")
                    option = input()
                    if option == '1':
                        print(show_credentials(a_list))
                    elif option == '2':
                        print("Which account would you like to delete?")
                        name = input()
                        delete_credential(name,a_list)
                        print(show_credentials(a_list))

                elif shortcode == '2':
                    exit()

        else: 
            print("Try again")
                            
if __name__ == '__main__':

    main()



